name: Composer Update

on:
  schedule:
    - cron: '0 0 * * 0' # This will run every Sunday at midnight
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Specify your PHP version
          tools: composer

      - name: Update Composer dependencies
        run: composer update

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add composer.json composer.lock
          git commit -m "Automated Composer update" || echo "No changes to commit"
          git push
